# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=200)),
                ('is_russian', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_band', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VkArtistRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks_count', models.IntegerField(default=0)),
                ('in_popular_count', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Artist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.SessionState')),
            ],
        ),
        migrations.CreateModel(
            name='VkPopularsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.SessionState'),
        ),
    ]
